linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - someword

  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false

  gosec:
    # To select a subset of rules to run.
    # Available rules: https://github.com/securego/gosec#available-rules
    includes:
      - G401
      - G306
      - G101
      - G102
      - G103
      - G104
      - G106
      - G107
      - G108
      - G109
      - G110

linters:
  disable-all: true
  enable:
    - errcheck
    - deadcode
    - goerr113
    - gosimple
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - dupl
    - gofmt
    - misspell
    - nilerr
    - unconvert
    - unparam
  fast: false
