// Code generated by go-swagger; DO NOT EDIT.

//
//   Copyright (c) 2022 Intel Corporation.
//
//   SPDX-License-Identifier: Apache-2.0
//
//
//

package ep

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Clustermanifest clustermanifest
//
// swagger:model clustermanifest
type Clustermanifest struct {

	// capi cluster providers
	CapiClusterProviders []*ClustermanifestCapiClusterProvidersItems0 `json:"capi_cluster_providers"`

	// cluster providers
	ClusterProviders []*ClustermanifestClusterProvidersItems0 `json:"cluster_providers"`
}

// Validate validates this clustermanifest
func (m *Clustermanifest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCapiClusterProviders(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterProviders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Clustermanifest) validateCapiClusterProviders(formats strfmt.Registry) error {
	if swag.IsZero(m.CapiClusterProviders) { // not required
		return nil
	}

	for i := 0; i < len(m.CapiClusterProviders); i++ {
		if swag.IsZero(m.CapiClusterProviders[i]) { // not required
			continue
		}

		if m.CapiClusterProviders[i] != nil {
			if err := m.CapiClusterProviders[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("capi_cluster_providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("capi_cluster_providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Clustermanifest) validateClusterProviders(formats strfmt.Registry) error {
	if swag.IsZero(m.ClusterProviders) { // not required
		return nil
	}

	for i := 0; i < len(m.ClusterProviders); i++ {
		if swag.IsZero(m.ClusterProviders[i]) { // not required
			continue
		}

		if m.ClusterProviders[i] != nil {
			if err := m.ClusterProviders[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cluster_providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cluster_providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this clustermanifest based on the context it is used
func (m *Clustermanifest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCapiClusterProviders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClusterProviders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Clustermanifest) contextValidateCapiClusterProviders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CapiClusterProviders); i++ {

		if m.CapiClusterProviders[i] != nil {
			if err := m.CapiClusterProviders[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("capi_cluster_providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("capi_cluster_providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Clustermanifest) contextValidateClusterProviders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ClusterProviders); i++ {

		if m.ClusterProviders[i] != nil {
			if err := m.ClusterProviders[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cluster_providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cluster_providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Clustermanifest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Clustermanifest) UnmarshalBinary(b []byte) error {
	var res Clustermanifest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestCapiClusterProvidersItems0 clustermanifest capi cluster providers items0
//
// swagger:model ClustermanifestCapiClusterProvidersItems0
type ClustermanifestCapiClusterProvidersItems0 struct {

	// binaries
	Binaries []*ClustermanifestCapiClusterProvidersItems0BinariesItems0 `json:"binaries"`

	// cert manager
	// Required: true
	CertManager *ClustermanifestCapiClusterProvidersItems0CertManager `json:"cert-manager"`

	// images
	Images []string `json:"images"`

	// name
	// Required: true
	// Enum: [metal3 byoh]
	Name *string `json:"name"`

	// providers
	// Required: true
	Providers Provider `json:"providers"`

	// runtime
	// Required: true
	// Enum: [containerd crio]
	Runtime *string `json:"runtime"`
}

func (m *ClustermanifestCapiClusterProvidersItems0) UnmarshalJSON(b []byte) error {
	type ClustermanifestCapiClusterProvidersItems0Alias ClustermanifestCapiClusterProvidersItems0
	var t ClustermanifestCapiClusterProvidersItems0Alias
	if err := json.Unmarshal([]byte("{\"runtime\":\"containerd\"}"), &t); err != nil {
		return err
	}
	if err := json.Unmarshal(b, &t); err != nil {
		return err
	}
	*m = ClustermanifestCapiClusterProvidersItems0(t)
	return nil
}

// Validate validates this clustermanifest capi cluster providers items0
func (m *ClustermanifestCapiClusterProvidersItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBinaries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCertManager(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProviders(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuntime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) validateBinaries(formats strfmt.Registry) error {
	if swag.IsZero(m.Binaries) { // not required
		return nil
	}

	for i := 0; i < len(m.Binaries); i++ {
		if swag.IsZero(m.Binaries[i]) { // not required
			continue
		}

		if m.Binaries[i] != nil {
			if err := m.Binaries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("binaries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("binaries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) validateCertManager(formats strfmt.Registry) error {

	if err := validate.Required("cert-manager", "body", m.CertManager); err != nil {
		return err
	}

	if m.CertManager != nil {
		if err := m.CertManager.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cert-manager")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cert-manager")
			}
			return err
		}
	}

	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) validateImages(formats strfmt.Registry) error {
	if swag.IsZero(m.Images) { // not required
		return nil
	}

	for i := 0; i < len(m.Images); i++ {

		if err := validate.Pattern("images"+"."+strconv.Itoa(i), "body", m.Images[i], `^[a-zA-Z0-9][a-zA-Z_.\-/:@0-9]*[a-zA-Z0-9]$`); err != nil {
			return err
		}

	}

	return nil
}

var clustermanifestCapiClusterProvidersItems0TypeNamePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["metal3","byoh"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clustermanifestCapiClusterProvidersItems0TypeNamePropEnum = append(clustermanifestCapiClusterProvidersItems0TypeNamePropEnum, v)
	}
}

const (

	// ClustermanifestCapiClusterProvidersItems0NameMetal3 captures enum value "metal3"
	ClustermanifestCapiClusterProvidersItems0NameMetal3 string = "metal3"

	// ClustermanifestCapiClusterProvidersItems0NameByoh captures enum value "byoh"
	ClustermanifestCapiClusterProvidersItems0NameByoh string = "byoh"
)

// prop value enum
func (m *ClustermanifestCapiClusterProvidersItems0) validateNameEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, clustermanifestCapiClusterProvidersItems0TypeNamePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	// value enum
	if err := m.validateNameEnum("name", "body", *m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) validateProviders(formats strfmt.Registry) error {

	if err := validate.Required("providers", "body", m.Providers); err != nil {
		return err
	}

	if err := m.Providers.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("providers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("providers")
		}
		return err
	}

	return nil
}

var clustermanifestCapiClusterProvidersItems0TypeRuntimePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["containerd","crio"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clustermanifestCapiClusterProvidersItems0TypeRuntimePropEnum = append(clustermanifestCapiClusterProvidersItems0TypeRuntimePropEnum, v)
	}
}

const (

	// ClustermanifestCapiClusterProvidersItems0RuntimeContainerd captures enum value "containerd"
	ClustermanifestCapiClusterProvidersItems0RuntimeContainerd string = "containerd"

	// ClustermanifestCapiClusterProvidersItems0RuntimeCrio captures enum value "crio"
	ClustermanifestCapiClusterProvidersItems0RuntimeCrio string = "crio"
)

// prop value enum
func (m *ClustermanifestCapiClusterProvidersItems0) validateRuntimeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, clustermanifestCapiClusterProvidersItems0TypeRuntimePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) validateRuntime(formats strfmt.Registry) error {

	if err := validate.Required("runtime", "body", m.Runtime); err != nil {
		return err
	}

	// value enum
	if err := m.validateRuntimeEnum("runtime", "body", *m.Runtime); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this clustermanifest capi cluster providers items0 based on the context it is used
func (m *ClustermanifestCapiClusterProvidersItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBinaries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCertManager(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProviders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) contextValidateBinaries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Binaries); i++ {

		if m.Binaries[i] != nil {
			if err := m.Binaries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("binaries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("binaries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) contextValidateCertManager(ctx context.Context, formats strfmt.Registry) error {

	if m.CertManager != nil {
		if err := m.CertManager.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cert-manager")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cert-manager")
			}
			return err
		}
	}

	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0) contextValidateProviders(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Providers.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("providers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("providers")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestCapiClusterProvidersItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestCapiClusterProvidersItems0) UnmarshalBinary(b []byte) error {
	var res ClustermanifestCapiClusterProvidersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestCapiClusterProvidersItems0BinariesItems0 clustermanifest capi cluster providers items0 binaries items0
//
// swagger:model ClustermanifestCapiClusterProvidersItems0BinariesItems0
type ClustermanifestCapiClusterProvidersItems0BinariesItems0 struct {

	// name
	// Pattern: ^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$
	Name string `json:"name,omitempty"`

	// revision
	Revision string `json:"revision,omitempty"`

	// sha256
	Sha256 string `json:"sha256,omitempty"`

	// url
	// Pattern: (?:(?:https?|http|ftp|file|oci)://|www.|ftp.)(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[-A-Z0-9+&@#/%=~_|$?!:,.])*(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[A-Z0-9+&@#/%=~_|$])
	URL string `json:"url,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this clustermanifest capi cluster providers items0 binaries items0
func (m *ClustermanifestCapiClusterProvidersItems0BinariesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0BinariesItems0) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", m.Name, `^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$`); err != nil {
		return err
	}

	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0BinariesItems0) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.Pattern("url", "body", m.URL, `(?:(?:https?|http|ftp|file|oci)://|www.|ftp.)(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[-A-Z0-9+&@#/%=~_|$?!:,.])*(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[A-Z0-9+&@#/%=~_|$])`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this clustermanifest capi cluster providers items0 binaries items0 based on context it is used
func (m *ClustermanifestCapiClusterProvidersItems0BinariesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestCapiClusterProvidersItems0BinariesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestCapiClusterProvidersItems0BinariesItems0) UnmarshalBinary(b []byte) error {
	var res ClustermanifestCapiClusterProvidersItems0BinariesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestCapiClusterProvidersItems0CertManager clustermanifest capi cluster providers items0 cert manager
//
// swagger:model ClustermanifestCapiClusterProvidersItems0CertManager
type ClustermanifestCapiClusterProvidersItems0CertManager struct {

	// url
	// Pattern: (?:(?:https?|http|ftp|file|oci)://|www.|ftp.)(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[-A-Z0-9+&@#/%=~_|$?!:,.])*(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[A-Z0-9+&@#/%=~_|$])
	URL string `json:"url,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this clustermanifest capi cluster providers items0 cert manager
func (m *ClustermanifestCapiClusterProvidersItems0CertManager) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestCapiClusterProvidersItems0CertManager) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.Pattern("cert-manager"+"."+"url", "body", m.URL, `(?:(?:https?|http|ftp|file|oci)://|www.|ftp.)(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[-A-Z0-9+&@#/%=~_|$?!:,.])*(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[A-Z0-9+&@#/%=~_|$])`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this clustermanifest capi cluster providers items0 cert manager based on context it is used
func (m *ClustermanifestCapiClusterProvidersItems0CertManager) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestCapiClusterProvidersItems0CertManager) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestCapiClusterProvidersItems0CertManager) UnmarshalBinary(b []byte) error {
	var res ClustermanifestCapiClusterProvidersItems0CertManager
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestClusterProvidersItems0 clustermanifest cluster providers items0
//
// swagger:model ClustermanifestClusterProvidersItems0
type ClustermanifestClusterProvidersItems0 struct {

	// binaries
	Binaries []*ClustermanifestClusterProvidersItems0BinariesItems0 `json:"binaries"`

	// images
	Images []*ClustermanifestClusterProvidersItems0ImagesItems0 `json:"images"`

	// name
	// Pattern: ^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$
	Name string `json:"name,omitempty"`

	// registrystorage
	// Pattern: ^[a-zA-Z.\/][a-zA-Z0-9-_.\/]*$
	Registrystorage string `json:"registrystorage,omitempty"`

	// resources
	Resources []*ClustermanifestClusterProvidersItems0ResourcesItems0 `json:"resources"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this clustermanifest cluster providers items0
func (m *ClustermanifestClusterProvidersItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBinaries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegistrystorage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestClusterProvidersItems0) validateBinaries(formats strfmt.Registry) error {
	if swag.IsZero(m.Binaries) { // not required
		return nil
	}

	for i := 0; i < len(m.Binaries); i++ {
		if swag.IsZero(m.Binaries[i]) { // not required
			continue
		}

		if m.Binaries[i] != nil {
			if err := m.Binaries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("binaries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("binaries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0) validateImages(formats strfmt.Registry) error {
	if swag.IsZero(m.Images) { // not required
		return nil
	}

	for i := 0; i < len(m.Images); i++ {
		if swag.IsZero(m.Images[i]) { // not required
			continue
		}

		if m.Images[i] != nil {
			if err := m.Images[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("images" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", m.Name, `^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$`); err != nil {
		return err
	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0) validateRegistrystorage(formats strfmt.Registry) error {
	if swag.IsZero(m.Registrystorage) { // not required
		return nil
	}

	if err := validate.Pattern("registrystorage", "body", m.Registrystorage, `^[a-zA-Z.\/][a-zA-Z0-9-_.\/]*$`); err != nil {
		return err
	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0) validateResources(formats strfmt.Registry) error {
	if swag.IsZero(m.Resources) { // not required
		return nil
	}

	for i := 0; i < len(m.Resources); i++ {
		if swag.IsZero(m.Resources[i]) { // not required
			continue
		}

		if m.Resources[i] != nil {
			if err := m.Resources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this clustermanifest cluster providers items0 based on the context it is used
func (m *ClustermanifestClusterProvidersItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBinaries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestClusterProvidersItems0) contextValidateBinaries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Binaries); i++ {

		if m.Binaries[i] != nil {
			if err := m.Binaries[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("binaries" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("binaries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0) contextValidateImages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Images); i++ {

		if m.Images[i] != nil {
			if err := m.Images[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("images" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0) contextValidateResources(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Resources); i++ {

		if m.Resources[i] != nil {
			if err := m.Resources[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0) UnmarshalBinary(b []byte) error {
	var res ClustermanifestClusterProvidersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestClusterProvidersItems0BinariesItems0 clustermanifest cluster providers items0 binaries items0
//
// swagger:model ClustermanifestClusterProvidersItems0BinariesItems0
type ClustermanifestClusterProvidersItems0BinariesItems0 struct {

	// name
	// Pattern: ^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$
	Name string `json:"name,omitempty"`

	// sha256
	Sha256 string `json:"sha256,omitempty"`

	// url
	// Pattern: (?:(?:https?|http|ftp|file|oci)://|www.|ftp.)(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[-A-Z0-9+&@#/%=~_|$?!:,.])*(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[A-Z0-9+&@#/%=~_|$])
	URL string `json:"url,omitempty"`
}

// Validate validates this clustermanifest cluster providers items0 binaries items0
func (m *ClustermanifestClusterProvidersItems0BinariesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestClusterProvidersItems0BinariesItems0) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", m.Name, `^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$`); err != nil {
		return err
	}

	return nil
}

func (m *ClustermanifestClusterProvidersItems0BinariesItems0) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.Pattern("url", "body", m.URL, `(?:(?:https?|http|ftp|file|oci)://|www.|ftp.)(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[-A-Z0-9+&@#/%=~_|$?!:,.])*(?:([-A-Z0-9+&@#/%=~_|$?!:,.]*)|[A-Z0-9+&@#/%=~_|$])`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this clustermanifest cluster providers items0 binaries items0 based on context it is used
func (m *ClustermanifestClusterProvidersItems0BinariesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0BinariesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0BinariesItems0) UnmarshalBinary(b []byte) error {
	var res ClustermanifestClusterProvidersItems0BinariesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestClusterProvidersItems0ImagesItems0 clustermanifest cluster providers items0 images items0
//
// swagger:model ClustermanifestClusterProvidersItems0ImagesItems0
type ClustermanifestClusterProvidersItems0ImagesItems0 struct {

	// name
	// Pattern: ^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$
	Name string `json:"name,omitempty"`

	// repo tag
	RepoTag string `json:"repo_tag,omitempty"`
}

// Validate validates this clustermanifest cluster providers items0 images items0
func (m *ClustermanifestClusterProvidersItems0ImagesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestClusterProvidersItems0ImagesItems0) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", m.Name, `^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this clustermanifest cluster providers items0 images items0 based on context it is used
func (m *ClustermanifestClusterProvidersItems0ImagesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0ImagesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0ImagesItems0) UnmarshalBinary(b []byte) error {
	var res ClustermanifestClusterProvidersItems0ImagesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClustermanifestClusterProvidersItems0ResourcesItems0 clustermanifest cluster providers items0 resources items0
//
// swagger:model ClustermanifestClusterProvidersItems0ResourcesItems0
type ClustermanifestClusterProvidersItems0ResourcesItems0 struct {

	// name
	// Pattern: ^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$
	Name string `json:"name,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this clustermanifest cluster providers items0 resources items0
func (m *ClustermanifestClusterProvidersItems0ResourcesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustermanifestClusterProvidersItems0ResourcesItems0) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", m.Name, `^[a-zA-Z_$][a-zA-Z_.\-$0-9]*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this clustermanifest cluster providers items0 resources items0 based on context it is used
func (m *ClustermanifestClusterProvidersItems0ResourcesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0ResourcesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustermanifestClusterProvidersItems0ResourcesItems0) UnmarshalBinary(b []byte) error {
	var res ClustermanifestClusterProvidersItems0ResourcesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
