#
# Copyright (c) 2022 Intel Corporation. 
#
# SPDX-License-Identifier: Apache-2.0
#
#
{{- block "ESP_Config" .}}{{ if .Extensions}}{{range .Extensions}}
{{- if eq .Name "esp_network" -}}
{{- range .Extension.Extension -}}
{{ if eq .Name "esp_network_topologic" }}

{{- range .Config -}}

{{- if eq .Name "host_ip" -}}
{{ if .Value }}
host_ip: {{ .Value }}
{{- end -}}
{{- end -}}
{{- if eq .Name "dhcp_range_minimum" -}}
{{ if .Value }}
dhcp_range_minimum: {{ .Value }}
{{- end -}}
{{- end -}}
{{- if eq .Name "dhcp_range_maximum" -}}
{{ if .Value }}
dhcp_range_maximum: {{ .Value }}
{{- end -}}
{{- end -}}

{{- if eq .Name "network_broadcast_ip" -}}
{{ if .Value }}
network_broadcast_ip: {{ .Value }}
{{- end -}}
{{- end -}}
{{- if eq .Name "network_gateway_ip" -}}
{{ if .Value }}
network_gateway_ip: {{ .Value }}
{{- end -}}
{{- end -}}
{{- if eq .Name "network_dns_primary" -}}
{{ if .Value }}
network_dns_primary: {{ .Value }}
{{- end -}}
{{- end -}}
{{- if eq .Name "network_dns_secondary" -}}
{{ if .Value }}
network_dns_secondary: {{ .Value }}
{{- end -}}
{{- end -}}


{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}{{- end -}}{{- end -}}


{{- block "Node_Config" .}}{{range $i, $v := .Kitconfig.Parameters.Nodes }}
{{if .IP }}
{{if .Mac }}
dhcp-host{{ $i }}: {{ .Mac }},{{ .IP }}
{{- end -}}
{{- end -}}
{{- end -}}{{- end -}}

{{- block "empty" .}}
{{ "\n" }}
{{- end -}}


profiles:
  - git_remote_url: file:///opt/localprofiles/.git
    profile_branch: main
    profile_base_branch: main
    git_username: ""
    git_token: ""
    # This is the name that will be shown on the PXE menu (NOTE: No Spaces)
    name: Ubuntu_20.04
    custom_git_arguments: --depth=1
