// Code generated by go-swagger; DO NOT EDIT.

//
//   Copyright (c) 2022 Intel Corporation.
//
//   SPDX-License-Identifier: Apache-2.0
//
//
//

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Filecontent filecontent
//
// swagger:model filecontent
type Filecontent struct {

	// content
	Content string `json:"content,omitempty"`
}

// Validate validates this filecontent
func (m *Filecontent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this filecontent based on context it is used
func (m *Filecontent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Filecontent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Filecontent) UnmarshalBinary(b []byte) error {
	var res Filecontent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
